// Mocks generated by Mockito 5.3.2 from annotations
// in core/test/presentation/cubit/series_watchlist/series_watchlist_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/domain/entities/series.dart' as _i7;
import 'package:core/domain/entities/series_detail.dart' as _i10;
import 'package:core/domain/repositories/series_repository.dart' as _i3;
import 'package:core/domain/usecases/get_watchlist_series.dart' as _i4;
import 'package:core/domain/usecases/get_watchlist_series_status.dart' as _i8;
import 'package:core/domain/usecases/remove_watchlist_series.dart' as _i11;
import 'package:core/domain/usecases/save_watchlist_series.dart' as _i9;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeriesRepository_1 extends _i1.SmartFake
    implements _i3.SeriesRepository {
  _FakeSeriesRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWatchlistSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistSeries extends _i1.Mock
    implements _i4.GetWatchlistSeries {
  MockGetWatchlistSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Series>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.Series>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.Series>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Series>>>);
}

/// A class which mocks [GetWatchListSeriesStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListSeriesStatus extends _i1.Mock
    implements _i8.GetWatchListSeriesStatus {
  MockGetWatchListSeriesStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SeriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSeriesRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.SeriesRepository);
  @override
  _i5.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SaveWatchListSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchListSeries extends _i1.Mock
    implements _i9.SaveWatchListSeries {
  MockSaveWatchListSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SeriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSeriesRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.SeriesRepository);
  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> execute(
          _i10.SeriesDetail? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [series],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [series],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchListSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchListSeries extends _i1.Mock
    implements _i11.RemoveWatchListSeries {
  MockRemoveWatchListSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SeriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSeriesRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.SeriesRepository);
  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> execute(
          _i10.SeriesDetail? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [series],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [series],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);
}
