// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLn7TcI7-npCjPi4It6XOA-TloK8YSL10',
    appId: '1:64680098722:web:ac88c020ea4d842f5590fb',
    messagingSenderId: '64680098722',
    projectId: 'ditonton-a7ae5',
    authDomain: 'ditonton-a7ae5.firebaseapp.com',
    storageBucket: 'ditonton-a7ae5.appspot.com',
    measurementId: 'G-FW1JC6E7KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_cVsgYE_agWTK8vW8qjgp_yBVWDXI6g4',
    appId: '1:64680098722:android:943b3db376b46b7f5590fb',
    messagingSenderId: '64680098722',
    projectId: 'ditonton-a7ae5',
    storageBucket: 'ditonton-a7ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtqGuFcmtzQG27M-E7f_dmUuHMtWzCHCw',
    appId: '1:64680098722:ios:46f11c93cd2ace015590fb',
    messagingSenderId: '64680098722',
    projectId: 'ditonton-a7ae5',
    storageBucket: 'ditonton-a7ae5.appspot.com',
    iosClientId: '64680098722-d0e5h5pfti81kucs83dsbb9ct27v0h3e.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
