// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDhJRmYu2vlsKQVBlppn6BF0c6fsOphI0',
    appId: '1:443524404430:web:0fd78d37ae14706a15ac9f',
    messagingSenderId: '443524404430',
    projectId: 'ditonton-c3104',
    authDomain: 'ditonton-c3104.firebaseapp.com',
    storageBucket: 'ditonton-c3104.appspot.com',
    measurementId: 'G-0Y5LG27BRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa2ext_cinSWd9WrK2Uzw8DLZHRjXbGxI',
    appId: '1:443524404430:android:cb4c686fd33164a215ac9f',
    messagingSenderId: '443524404430',
    projectId: 'ditonton-c3104',
    storageBucket: 'ditonton-c3104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3a2JzxQSRVozFuo2WSiLy1b1qzPjAg7Y',
    appId: '1:443524404430:ios:febfbffa5a48f29315ac9f',
    messagingSenderId: '443524404430',
    projectId: 'ditonton-c3104',
    storageBucket: 'ditonton-c3104.appspot.com',
    iosClientId: '443524404430-76btrtnvos60ahek3e2andcai9f1i0qd.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
